/*
 * NOT generated by Speakeasy. Hand-written companion that adds `$filter` and
 * `cursor` to every list operation — features ServiceM8's REST API supports
 * (https://developer.servicem8.com/docs/filtering and /docs/pagination) but
 * which their openapi.json does not enumerate on per-operation `parameters`.
 *
 * Hooked into `createRegisterTool` in tools.ts with a single line; the rest
 * of the SDK is unmodified. Speakeasy regen only touches Speakeasy-emitted
 * files, so this file survives upstream regenerations.
 *
 * Detection rule: list operations carry the literal annotation
 *   "supports result filtering"
 * in their generated description.
 *
 * On a match we replace the description with a compact, markdown block
 * that includes the actual snake_case filterable field set for that
 * resource (extracted at module load from `<Resource>$inboundSchema`,
 * which Speakeasy declares with the wire-format keys). The LLM no longer
 * has to guess between camelCase TS-side names and snake_case wire-side
 * names.
 */

import { AsyncLocalStorage } from "node:async_hooks";
import { z, type ZodRawShape } from "zod/v3";
import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js";
import type { ToolDefinition } from "./tools.js";
import { FILTER_FIELD_MAP } from "./_filter-field-map.js";

const FILTER_ANNOTATION = "supports result filtering";

// Resource → snake_case field list, generated at build time by
// _gen-filter-fields.mjs from the SDK's `<Resource>$inboundSchema` declarations
// (those are declared with the wire-format snake_case keys ServiceM8 expects
// in `$filter` URLs). Runtime Zod reflection didn't survive the Bun bundler's
// renames, so we ship a static map instead.
function fieldsFor(resource: string): readonly string[] | undefined {
  return FILTER_FIELD_MAP[resource];
}

// ──────────────────────────────────────────────────────────────────────────
// Tool name → resource name. Tool pattern is `<plural-kebab>-list-<plural-kebab>`.
// ──────────────────────────────────────────────────────────────────────────

function singularize(s: string): string {
  if (s.endsWith("ies")) return s.slice(0, -3) + "y";
  if (s.endsWith("ses") || s.endsWith("xes")) return s.slice(0, -2);
  if (s.endsWith("s") && !s.endsWith("ss")) return s.slice(0, -1);
  return s;
}

function pascalCase(s: string): string {
  return s
    .split("-")
    .map((p) => (p ? p[0]!.toUpperCase() + p.slice(1) : ""))
    .join("");
}

function resourceFromToolName(name: string): string {
  const idx = name.indexOf("-list-");
  const plural = idx >= 0 ? name.slice(idx + "-list-".length) : name;
  return pascalCase(singularize(plural));
}

// ──────────────────────────────────────────────────────────────────────────
// Compact description builder. Strips Speakeasy's verbose trailing
// `#### Filtering / #### OAuth Scope / #### Record UUID` boilerplate and
// emits a tight markdown block with the actual snake_case field list.
// ──────────────────────────────────────────────────────────────────────────

function buildDescription(toolName: string, originalDesc: string): string {
  const resource = resourceFromToolName(toolName);
  const fields = fieldsFor(resource);

  // Keep only the first non-empty line of the original (the "List all X" hint).
  const firstLine = (originalDesc.split("\n").find((l) => l.trim()) || "").trim();
  const summary = firstLine || `List ${resource} records.`;

  const fieldLine = fields && fields.length
    ? `Fields (snake_case, verbatim): ${fields.map((f) => `\`${f}\``).join(", ")}.`
    : "Fields: probe with `cursor='-1'` and no filter, then inspect snake_case keys in `records[0]`.";

  return [
    summary,
    "",
    "`filter` (OData, raw — do NOT url-encode): operators `eq`/`ne`/`gt`/`lt` joined with `and` (max 10, no `or`/`not`/parens). Strings single-quoted, numbers unquoted.",
    fieldLine,
    "Examples: `active eq 1`, `date gt '2026-01-01' and active eq 1`.",
    "",
    "`cursor`: pass `'-1'` for first page; subsequent calls pass `next_cursor` from the previous response. `null` = last page.",
  ].join("\n");
}

// ──────────────────────────────────────────────────────────────────────────
// Per-call slot + global fetch patch (idempotent across module re-evals).
// ──────────────────────────────────────────────────────────────────────────

type Slot = { filter?: string; cursor?: string; nextCursor?: string };
const slotStorage = new AsyncLocalStorage<Slot>();

const FETCH_PATCH_FLAG = Symbol.for("__sm8_filter_cursor_fetch_patched__");

function patchFetchOnce(): void {
  const g = globalThis as unknown as Record<symbol, unknown> & {
    fetch: typeof fetch;
  };
  if (g[FETCH_PATCH_FLAG]) return;
  g[FETCH_PATCH_FLAG] = true;

  const originalFetch = g.fetch;
  g.fetch = async (input, init) => {
    const slot = slotStorage.getStore();
    let actualInput: RequestInfo | URL = input;

    if (slot && (slot.filter || slot.cursor)) {
      const urlStr =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : (input as Request).url;
      const url = new URL(urlStr);
      if (slot.filter && !url.searchParams.has("$filter")) {
        url.searchParams.set("$filter", slot.filter);
      }
      if (slot.cursor && !url.searchParams.has("cursor")) {
        url.searchParams.set("cursor", slot.cursor);
      }
      actualInput =
        input instanceof Request
          ? new Request(url.toString(), input)
          : url.toString();
    }

    const response = await originalFetch(actualInput, init);

    if (slot) {
      const next = response.headers.get("x-next-cursor");
      if (next) slot.nextCursor = next;
    }
    return response;
  };
}

// ──────────────────────────────────────────────────────────────────────────
// The augmenter — called once per ToolDefinition at registration time.
// ──────────────────────────────────────────────────────────────────────────

type AnyToolDefinition = ToolDefinition<ZodRawShape | undefined>;

const FILTER_DESC =
  "OData expression. Operators `eq`/`ne`/`gt`/`lt` joined with `and`. " +
  "Strings single-quoted. See the tool description for the snake_case " +
  "field list — do not guess field names.";

const CURSOR_DESC =
  "Pagination cursor. `'-1'` for first page; subsequent calls pass " +
  "`next_cursor` from the previous response. `null` = last page.";

export function augmentListTool<A extends ZodRawShape | undefined>(
  def: ToolDefinition<A>,
): ToolDefinition<ZodRawShape> | ToolDefinition<A> {
  if (!def.description?.includes(FILTER_ANNOTATION)) return def;

  patchFetchOnce();

  const baseArgs: ZodRawShape = (def.args as unknown as ZodRawShape) ?? {};
  const augmentedArgs: ZodRawShape = {
    ...baseArgs,
    filter: z.string().optional().describe(FILTER_DESC),
    cursor: z.string().optional().describe(CURSOR_DESC),
  };

  const originalTool = (def as AnyToolDefinition).tool;

  const wrapped: ToolDefinition<ZodRawShape> = {
    ...(def as AnyToolDefinition),
    description: buildDescription(def.name, def.description ?? ""),
    args: augmentedArgs,
    tool: async (sdk, args, ctx) => {
      const a = (args ?? {}) as Record<string, unknown>;
      const slot: Slot = {
        filter: typeof a["filter"] === "string" ? (a["filter"] as string) : undefined,
        cursor: typeof a["cursor"] === "string" ? (a["cursor"] as string) : undefined,
      };
      // Strip our injected keys before forwarding to the original callback so
      // the generated tool's zod parse never sees unknown args.
      const { filter: _f, cursor: _c, ...rest } = a;
      void _f; void _c;

      const result: CallToolResult = await slotStorage.run(slot, () =>
        Promise.resolve(originalTool(sdk, rest as never, ctx)),
      );

      // Wrap list results as { records, next_cursor } so the agent has a
      // stable shape and can paginate.
      if (
        !result.isError
        && Array.isArray(result.content)
        && result.content.length === 1
        && result.content[0]
        && (result.content[0] as { type?: string }).type === "text"
      ) {
        const text = (result.content[0] as { text: string }).text;
        try {
          const parsed: unknown = JSON.parse(text);
          const wrappedBody = {
            records: parsed,
            next_cursor: slot.nextCursor ?? null,
          };
          return {
            ...result,
            content: [{ type: "text", text: JSON.stringify(wrappedBody) }],
          };
        } catch {
          // Not JSON — leave the result untouched.
        }
      }
      return result;
    },
  };

  return wrapped;
}
