/*
 * NOT generated by Speakeasy. Hand-written companion that adds `$filter` and
 * `cursor` to every list operation — features ServiceM8's REST API supports
 * (https://developer.servicem8.com/docs/filtering and /docs/pagination) but
 * which their openapi.json does not enumerate on per-operation `parameters`.
 *
 * Hooked into `createRegisterTool` in tools.ts with a single line; the rest
 * of the SDK is unmodified. Speakeasy regen only touches Speakeasy-emitted
 * files, so this file survives upstream regenerations.
 *
 * Detection rule: list operations carry the literal annotation
 *   "supports result filtering"
 * in their generated description. That's the only set we touch.
 *
 * Mechanism:
 *   - Augment the ToolDefinition: add optional `filter` + `cursor` Zod args
 *     and prepend a usage preamble to the description.
 *   - Wrap the tool callback with an AsyncLocalStorage frame holding the
 *     args.
 *   - Monkey-patch globalThis.fetch ONCE to: (a) append $filter / cursor to
 *     the outbound URL, (b) capture the response's x-next-cursor header.
 *   - On return, re-shape the tool result body into
 *     { records: <original>, next_cursor: <string|null> } so the agent can
 *     paginate without seeing the response headers.
 */

import { AsyncLocalStorage } from "node:async_hooks";
import { z, type ZodRawShape } from "zod/v3";
import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js";
import type { ToolDefinition } from "./tools.js";

const FILTER_ANNOTATION = "supports result filtering";

const FILTER_DESC =
  "OData-style filter expression applied server-side. Up to 10 conditions " +
  "joined with `and` (no `or`, no `not`, no parentheses). Operators: `eq`, " +
  "`ne`, `gt`, `lt`. String values in single quotes, numerics unquoted. " +
  "Examples: `active eq 1`, `status eq 'Work Order' and active eq 1`, " +
  "`date gt '2026-01-01' and active eq 1`. " +
  "Field names are case-sensitive snake_case and MUST appear in the " +
  "response shape — there is no `create_date`, use `date` (the job/record " +
  "date) or `edit_date` (last modified). If unsure, probe with " +
  "`cursor='-1'` and no filter, inspect the field names returned, then " +
  "filter on a subsequent call. Pass the raw expression — do NOT URL-encode. " +
  "Max value length 255 chars. https://developer.servicem8.com/docs/filtering";

const CURSOR_DESC =
  "Pagination cursor. Pass `'-1'` for the first page; each response " +
  "returns up to 1000 records and a `next_cursor` field in the result. " +
  "To get the next page, pass that `next_cursor` value here. When " +
  "`next_cursor` is `null` in the response, you have reached the last " +
  "page. https://developer.servicem8.com/docs/pagination";

const USAGE_PREAMBLE =
  "\n#### USAGE\n" +
  "ALWAYS use `filter` to narrow results — never list a whole resource " +
  "just to scan client-side. The filter is applied server-side and " +
  "avoids pulling thousands of records.\n\n" +
  "For pagination: pass `cursor='-1'` on the first call. The response " +
  "will contain a `next_cursor` field — pass that value to fetch the " +
  "next page. When `next_cursor` is `null`, you have the last page.\n\n" +
  "Filter syntax (OData):\n" +
  "  active eq 1\n" +
  "  status eq 'Work Order' and active eq 1\n" +
  "  date gt '2026-01-01' and active eq 1\n" +
  "  edit_date gt '2026-05-01' and active eq 1\n\n" +
  "Operators: eq, ne, gt, lt. Combine with `and` (max 10 conditions, no " +
  "or/not, no parens). Strings single-quoted, numerics unquoted.\n\n" +
  "FIELD DISCOVERY: filter field names must match the snake_case keys in " +
  "the response records. Common pitfalls: `create_date` does NOT exist — " +
  "use `date` for the job/record date or `edit_date` for last-modified. " +
  "If you don't know the schema, do a single probe call with `cursor='-1'` " +
  "and no filter, then inspect the field names in `records[0]` before " +
  "filtering on subsequent calls.\n";

// ──────────────────────────────────────────────────────────────────────────
// Per-call slot + global fetch patch (idempotent across module re-evals).
// ──────────────────────────────────────────────────────────────────────────
type Slot = { filter?: string; cursor?: string; nextCursor?: string };
const slotStorage = new AsyncLocalStorage<Slot>();

const FETCH_PATCH_FLAG = Symbol.for("__sm8_filter_cursor_fetch_patched__");

function patchFetchOnce(): void {
  const g = globalThis as unknown as Record<symbol, unknown> & {
    fetch: typeof fetch;
  };
  if (g[FETCH_PATCH_FLAG]) return;
  g[FETCH_PATCH_FLAG] = true;

  const originalFetch = g.fetch;
  g.fetch = async (input, init) => {
    const slot = slotStorage.getStore();
    let actualInput: RequestInfo | URL = input;

    if (slot && (slot.filter || slot.cursor)) {
      const urlStr =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : (input as Request).url;
      const url = new URL(urlStr);
      if (slot.filter && !url.searchParams.has("$filter")) {
        url.searchParams.set("$filter", slot.filter);
      }
      if (slot.cursor && !url.searchParams.has("cursor")) {
        url.searchParams.set("cursor", slot.cursor);
      }
      // Preserve Request-shape inputs so headers/body survive.
      actualInput =
        input instanceof Request
          ? new Request(url.toString(), input)
          : url.toString();
    }

    const response = await originalFetch(actualInput, init);

    if (slot) {
      const next = response.headers.get("x-next-cursor");
      if (next) slot.nextCursor = next;
    }
    return response;
  };
}

// ──────────────────────────────────────────────────────────────────────────
// The augmenter — called once per ToolDefinition at registration time.
// ──────────────────────────────────────────────────────────────────────────
type AnyToolDefinition = ToolDefinition<ZodRawShape | undefined>;

export function augmentListTool<A extends ZodRawShape | undefined>(
  def: ToolDefinition<A>,
): ToolDefinition<ZodRawShape> | ToolDefinition<A> {
  if (!def.description?.includes(FILTER_ANNOTATION)) return def;

  patchFetchOnce();

  const baseArgs: ZodRawShape = (def.args as unknown as ZodRawShape) ?? {};
  const augmentedArgs: ZodRawShape = {
    ...baseArgs,
    filter: z.string().optional().describe(FILTER_DESC),
    cursor: z.string().optional().describe(CURSOR_DESC),
  };

  const originalTool = (def as AnyToolDefinition).tool;

  const wrapped: ToolDefinition<ZodRawShape> = {
    ...(def as AnyToolDefinition),
    description: USAGE_PREAMBLE + (def.description ?? ""),
    args: augmentedArgs,
    tool: async (sdk, args, ctx) => {
      const a = (args ?? {}) as Record<string, unknown>;
      const slot: Slot = {
        filter: typeof a["filter"] === "string" ? (a["filter"] as string) : undefined,
        cursor: typeof a["cursor"] === "string" ? (a["cursor"] as string) : undefined,
      };
      // Strip our injected keys before forwarding to the original callback so
      // the generated tool's zod parse never sees unknown args.
      const { filter: _f, cursor: _c, ...rest } = a;
      void _f; void _c;

      const result: CallToolResult = await slotStorage.run(slot, () =>
        // The original tool may have had its own args (rare for list ops) or
        // none at all; pass whatever survives stripping.
        Promise.resolve(originalTool(sdk, rest as never, ctx)),
      );

      // Always wrap list results as { records, next_cursor } so the agent has
      // a stable shape and can paginate. Only wrap if the result is a single
      // text content block carrying JSON.
      if (
        !result.isError
        && Array.isArray(result.content)
        && result.content.length === 1
        && result.content[0]
        && (result.content[0] as { type?: string }).type === "text"
      ) {
        const text = (result.content[0] as { text: string }).text;
        try {
          const parsed: unknown = JSON.parse(text);
          const wrappedBody = {
            records: parsed,
            next_cursor: slot.nextCursor ?? null,
          };
          return {
            ...result,
            content: [{ type: "text", text: JSON.stringify(wrappedBody) }],
          };
        } catch {
          // Not JSON — leave the result untouched.
        }
      }
      return result;
    },
  };

  return wrapped;
}
